#ifndef MESSAGERECEIVERTYPE_H
#define MESSAGERECEIVERTYPE_H

namespace Engine {

enum class MessageReceiverType {
    UNKNOWN,

    CHARACTER_ACTION_UPDATE,
    CHARACTER_STRUCTURE_UPDATE,
    CHARACTER_LOCATION_UPDATE,

    CHARACTER_EQUIP_ITEM,
    CHARACTER_USE_ITEM,
    CHARACTER_CAST_SPELL,

    CHARACTER_INTERACT_DENIZEM,
    CHARACTER_TRADE_DENIZEN,
    CHARACTER_ACCEPT_DENIZEN_QUEST,
    CHARACTER_FINISH_DENIZEN_QUEST,

    COMBAT_ROOM_CREATE,
    COMBAT_ROOM_ENTER,
    COMBAT_ROOM_EXIT,
};

} // namespace Engine

#endif // MESSAGERECEIVERTYPE_H
