#ifndef MESSAGERECEIVERTYPE_H
#define MESSAGERECEIVERTYPE_H

namespace Engine {

enum class MessageReceiverType {
    UNKNOWN,

    CHARACTER_ACTION_UPDATE,

    CHARACTER_EQUIP_ITEM,
    CHARACTER_USE_ITEM,
    CHARACTER_CAST_SPELL,

    COMBAT_ROOM_CREATE,
    COMBAT_ROOM_ENTER,
    COMBAT_ROOM_EXIT,
};

} // namespace Engine

#endif // MESSAGERECEIVERTYPE_H
