#ifndef CHARACTEREVENTTYPE_H
#define CHARACTEREVENTTYPE_H

namespace Engine {

enum class CharacterEventType {
    ITEM_EQUIPPED,
    ITEM_GAINED,

    EFFECT_APPLY,

    PROGRESSION_EXPERIENCE_GAINED,
    PROGRESSION_LEVEL_GAINED,

    SKILL_EXPERIENCE_GAINED,
    SKILL_LEVEL_GAINED,

    VITAL_MAX_HEALTH_GAINED,
    VITAL_MAX_MANA_GAINED,
    VITAL_MAX_STAMINA_GAINED,
    VITAL_HEALTH_CHANGED,
    VITAL_MANA_CHANGED,
    VITAL_STAMINA_CHANGED,

    UNKNOWN,
};

} // namespace Engine

#endif // CHARACTEREVENTTYPE_H
