#ifndef MESSAGERECEIVERTYPE_H
#define MESSAGERECEIVERTYPE_H

namespace Core::Message {

enum class MessageReceiverType {
    UNKNOWN,

    CHARACTER_UPDATE_ACTION,
    CHARACTER_UPDATE_STRUCTURE,
    CHARACTER_UPDATE_LOCATION,

    COMBAT_ROOM_CREATE,
    COMBAT_ROOM_ENTER,
    COMBAT_ROOM_EXIT,
};

} // namespace Core::Message

#endif // MESSAGERECEIVERTYPE_H
